[workspace]
resolver = "2"

members = ["indexer-cli", "crates/*"]

[workspace.dependencies]
tsify = { version = "0.4.5", default-features = false }
erc20 = { git = "https://github.com/leruaa/erc20-rs" }
uniswapx = { git = "https://github.com/leruaa/uniswapx-rs" }
alloy-primitives = "0.6"
