[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
defillama = { git = "https://github.com/leruaa/defillama-rs" }
erc20 = { git = "https://github.com/leruaa/erc20-rs" }
uniswapx = { path = "../../../uniswapx-rs" }
ethers = { version = "2.0" }
stapifaction = { path = "../../../../stapifaction/stapifaction", features = [
    "json",
] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"
tracing = "0.1"
anyhow = "1.0"
